# configs/config.yaml

# 실행
mode: train # train or eval

# train mode
target_model_update_freq: 30
num_episodes: 2000
model_save_freq : 100
training_data_split : 1   #training dataset 비율 -> 현재는 test를 위해 1로 둠
log_save_freq: 100  # 몇 episode마다 로그를 저장할지

# evaluate mode
num_eval_episodes: 5
model_path: /home/songmu/Multipath/rl/data/results/2024_11_06_21_18/models/dqn_model_episode701.pth

# 환경 설정
frame_dir: data/frames/frames_og/
kt_log_dir: 'data/env_logs/kt_log.csv'
lg_log_dir: 'data/env_logs/lg_log.csv'
latency_threshold: 100  # ms
ssim_threshold: 0.85
gamma_reward: 0.1
max_datasize: 10000

# 에이전트 하이퍼파라미터
gamma: 0.99
epsilon_start: 0.15
epsilon_min: 0.05
epsilon_decay: 0.995
learning_rate: 0.001
batch_size: 16
memory_size: 1500
actions:
  0:
    - KT
    - I-frame
  1:
    - KT
    - P-frame
  2:
    - LG
    - I-frame
  3:
    - LG
    - P-frame
  4:
    - Both
    - I-frame
  5:
    - Both
    - P-frame

